# Generated by Django 3.2.6 on 2021-08-28 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
