# Generated by Django 3.2.6 on 2021-08-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lastName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
